export const contact = [
  {
    id: 145,
    name: "A&A Consulting (AEC) ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 135,
    name: "Lance Smith ingenieure (Etudes)",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 139,
    name: "Reece, Murphy & Technology",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 142,
    name: "Warwik Systemes & Technology",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 143,
    name: "Ville de Paris (Planing et Devlopment)",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
];
