export const data = [
  {
    id: 19,
    name: "tache a moi ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 21,
    name: "tache 1 a alaex",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 23,
    name: "tache 3 a alex ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
];
