export const fclient = [
  {
    id: 345,
    name: "Modele de Factures Client ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 237,
    name: "Factures No 1036 -GNT",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 238,
    name: "Facture No 1037 -UPS  ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
];
export const ffourniseure = [
  {
    id: 361,
    name: "Facture No 1035 -Factory Notte Associes  ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 240,
    name: "Facture client 240 ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 250,
    name: "Facture client 250  ",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
];
