export const raport = [
  {
    id: 19,
    name: "Complete de  Resultat 8/2006",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 21,
    name: "Complete de  Resultat 5/2007",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 23,
    name: "Complete de  Resultat 9/2006",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 19,
    name: "Complete de  Resultat 8/2006",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 21,
    name: "Complete de  Resultat 5/2007",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 23,
    name: "Complete de  Resultat 9/2006",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 19,
    name: "Complete de  Resultat 8/2006",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: "undefined",
    transite: new Date(),
    description: "undefined",
    echeance: "undefined",
    controle: "undefined",
    afecte: "undefined",
    marque: "undefined",
  },
  {
    id: 21,
    name: "Complete de  Resultat 5/2007",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
  {
    id: 23,
    name: "Complete de  Resultat 9/2006",
    modifie: new Date(),
    fichier: false,
    statutmodefie: new Date(),
    taille: 0,
    worflow: undefined,
    transite: new Date(),
    description: undefined,
    echeance: undefined,
    controle: undefined,
    afecte: undefined,
    marque: undefined,
  },
];
